name = "Traingame"
author = "rsap"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f07b6659affb4dd999164f1061743104e3f861a39f5e62f43915b5e634c832f3"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
