name = "Traingame"
author = "rsap"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f417924beb5b41d0b7a5bfc68d0bf386f9818f27244ea2de3def9cc129d6be7"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
