#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jun 18 21:26:37 IST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=Hysteria-Shaders-Universal-v1.2.1.zip
